# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Claug < Formula
  desc "CLI for claug — track and share your coding sessions"
  homepage "https://claug.ai"
  version "0.0.1-alpha1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/howinator/claug/releases/download/v0.0.1-alpha1/claug_darwin_amd64.tar.gz"
      sha256 "1c36a356cbe05501db02d9990f6f794ec2a71ae4c379833475c94fd47908d2e7"

      define_method(:install) do
        bin.install "claug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/howinator/claug/releases/download/v0.0.1-alpha1/claug_darwin_arm64.tar.gz"
      sha256 "c809143bccb6226f1b41ab355b976825f57fef847d3b98342c92cb969f2fe462"

      define_method(:install) do
        bin.install "claug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/howinator/claug/releases/download/v0.0.1-alpha1/claug_linux_amd64.tar.gz"
      sha256 "92bc16a11f4802614003bba7f986b691a03fd9bcb8e47aedc2e54e884b3f59eb"
      define_method(:install) do
        bin.install "claug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/howinator/claug/releases/download/v0.0.1-alpha1/claug_linux_arm64.tar.gz"
      sha256 "b5321532249105720882e208564baa40524d4d24ef4085f01ab69ad2e875a398"
      define_method(:install) do
        bin.install "claug"
      end
    end
  end

  test do
    system "#{bin}/claug", "--version"
  end
end
