# This file was generated by GoReleaser. DO NOT EDIT.
cask "claug" do
  name "claug"
  desc "CLI for claug — track and share your coding sessions"
  homepage "https://claug.ai"
  version "0.0.1-alpha1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claug"

  on_macos do
    on_intel do
      url "https://github.com/howinator/claug/releases/download/v#{version}/claug_darwin_amd64.tar.gz"
      sha256 "9a6c44999624069d58f6ea72b1d9e9e4f11462221ff18968b66097448cee5eb4"
    end
    on_arm do
      url "https://github.com/howinator/claug/releases/download/v#{version}/claug_darwin_arm64.tar.gz"
      sha256 "97574fc25b7899d9453ff3c3170dc69152c5a45a77893699d76d862d2974167a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/howinator/claug/releases/download/v#{version}/claug_linux_amd64.tar.gz"
      sha256 "979d9e512e1fc8dcf7319f46558a420cc2e336daf0b5a1f65b65edc1f9e70745"
    end
    on_arm do
      url "https://github.com/howinator/claug/releases/download/v#{version}/claug_linux_arm64.tar.gz"
      sha256 "00a7c677e518cf43dde3f62cea757aa574fa44434b023ebe01746e76a993d5df"
    end
  end

  # No zap stanza required
end
